[package]
name = "dispatch_and_fat_pointers"
version = "0.1.0"
authors = ["Aaron <armatrix@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
